<%@page import="friedman.tal.mfs.resources.ITimelineResource"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8" isELIgnored="false"%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>  
    	<!--  I was generated by a JSP -->
        <title>My Fibrolamellar Story</title>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />

        <link class="jqueryUICss" type="text/css" rel="stylesheet" href="/css/default/jquery-ui-1.9.2.custom.css" />

		<%-- include the correct CSS files --%>
		<c:choose>
			<c:when test="${requestScope.debugMode == true}">
				<%-- include the unminified CSS files since an admin is debugging this page --%>
				<c:choose>
					<c:when test="${isEditable}">
						<link id="appCss" type="text/css" rel="stylesheet" href="/css/timeline.css" />
						<link id="appCss" type="text/css" rel="stylesheet" href="/css/app.css" />
						<link id="appCss" type="text/css" rel="stylesheet" href="/css/editUI.css" />
					</c:when>
					<c:otherwise>
						<link id="appCss" type="text/css" rel="stylesheet" href="/css/timeline.css" />
						<link id="appCss" type="text/css" rel="stylesheet" href="/css/app.css" />						
					</c:otherwise>
				</c:choose>		
			</c:when>
			<c:otherwise>
				<%-- include the minified CSS files - end user demands max performance! :) --%>
				<c:choose>
					<c:when test="${isEditable}">
						<link id="appCss" type="text/css" rel="stylesheet" href="/css/timelineEditableApp.min.css" />
					</c:when>
					<c:otherwise>
						<link id="appCss" type="text/css" rel="stylesheet" href="/css/timelineApp.min.css" />
					</c:otherwise>
				</c:choose>		
			</c:otherwise>
		</c:choose>         
        
        <!-- <link id="appCss" type="text/css" rel="stylesheet" href="/css/timelineEditableApp.min.css" /> -->
        <link class="coloursCss" type="text/css" rel="stylesheet" href="/css/default/colours.css" />              


		<%--<%@ include file="/jspf/demoData.jspf" %>--%>
		<script type="text/x-events-json"  id="eventsToLoad">
			<%= request.getAttribute(ITimelineResource.EVENTS_JSON_ATTR_NAME) %>
		</script>
		<script type="text/x-events-json"  id="chaptersToLoad">
			<%= request.getAttribute(ITimelineResource.CHAPTERS_JSON_ATTR_NAME) %>
		</script>
		<script type="text/x-autocomplete-json"  id="doctorAutocompleteData">
			[
				"Marshall Schorin",
                "Patrick Travis",
                "Ahmed Kaseb",
                "Prashanti Atluri",
                "Stephen Cohen",
                "Emmanuel Zervos",
                "Winston Dunn",
                "Dr. Barry",
                "Richard J. Gualtieri",
                "Filip Janku",
                "Prasad S. Vankineni",
                "Sohaib Siddiqui",
                "Devon Evans",
                "Lisa Rutstein",
                "Tracey Wiegel",
                "J. N. Vauthey",
                "Steven Calquhoun",
                "Solomon Hamburg",
                "Michael Laquaglia",
                "David M. Nagorney",
                "Cifford Cho",
                "Stephen R Bartos",
                "Cynthia Herzog",
                "Paul Gibbs",
                "Graeme Alexander",
                "James Fuesner",
                "Robert Pelley",
                "Mir Ali",
                "Howard Gold",
                "Jeffery Schwartz",
                "Thomas Sunnenberg",
                "Harry Cramer",
                "Patrick Thompson"
			]
		</script>
        <script type="text/x-autocomplete-json"  id="hospitalAutocompleteData">
            [
                "Inova Fairfax",
                "Mercy Hospital",
                "MD Anderson Cancer Center",
                "Leo Jenkins Cancer Center",
                "Fox Chase Cancer Center",
                "University of Kansas Hospital",
                "Eastern Interventional Radiology",
                "Huntsville Hospital",
                "Saco River Medical Group",
                "Maine Center for Cancer Medicine",
                "Maine surgical care group",
                "Cedars Sanai Meical Center",
                "Tore Hematology Oncology",
                "Memorial Sloan Kettering Cancer Center",
                "Mayo Cinic",
                "University of Wisconsin Hospital",
                "Waukesha Memorial Hospital",
                "Texas Children's Hospital",
                "Sacred Heart Hospital",
                "Nemours Children's Hospital",
                "Canton-Potsdam Hospital",
                "Cleveland Clinic",
                "Childrens Hospital",
                "Addenbrookes Hospital"
            ]
        </script>
        <script type="text/x-autocomplete-json"  id="locationAutocompleteData">
            [ 
                "Fairfax, Virginia",
                "Rogers, AR  USA",
                "Houston, TX",
                "Greenville, NC",
                "Philadelphia, PA",
                "Kansas City, KS",
                "Huntsville AL",
                "Conway, NH",
                "Scarborough, ME",
                "Portland, ME",
                "Los Angeles, CA",
                "Beverly Hills, CA",
                "New York City, NY",
                "Rochester, MN",
                "Madison, WI",
                "Waukesha, WI",
                "Cambridge, UK",
                "Oakland, CA",
                "Cleveland, OH",
                "Potsdam, NY",
                "Pensacola, FL"
            ]
        </script>
        <script type="text/x-autocomplete-json"  id="chemoAutocompleteData">
            [
                "5FU (Fluorouracil) and Interferon Alpha", 
                "5FU (Fluorouracil) and Eloxatin (Oxaliplatin)", 
                "GEMOX - Gemzar (Gemcitabine) and Eloxatin (Oxaliplatin)", 
                "AVATAR - Avastin (Bevacizumab) and Tarceva (Erlotinib)",
                "Nexavar (Sorafenib)",
                "Sutent (Sunitinib)",
                "Linifanib",
                "5-FU (fluorouracil)",
                "Xeloda (capecitabine)",
                "Interferon Alpha",
                "Sutent (sunitinib)",
                "Eloxatin (oxaliplatin)",
                "Platinol (cisplatin)",
                "Adriamycin (doxorubicin)",
                "Gemzar (gemcitabine)",
                "Tarceva (erlotinib)",
                "Afinitor (everolimus)",
                "Alkeran (melphalan)",
                "Ara-C (cytarabine)",
                "Aredia (pamidronate)",
                "Arimidex (anastrozole)",
                "Aromasin (exemestane)",
                "Arranon (nelarabine)",
                "Avastin (bevacizumab)",
                "Bexxar (tositumomab)",
                "BiCNU (carmustine)",
                "Blenoxane (bleomycin)",
                "Campath (alemtuzumab)",
                "Camptosar (irinotecan)",
                "Casodex (bicalutamide)",
                "CeeNU (lomustine)",
                "Cerubidine (daunorubicin)",
                "Cosmegen (dactinomycin)",
                "Cytoxan (cyclophosphamide)",
                "Ellence (epirubicin)",
                "Elspar (asparaginase)",
                "Emcyt (estramustine)",
                "Erbitux (cetuximab)",
                "Ethyol (amifostine)",
                "Eulexin (flutamide)",
                "Fareston (toremifene)",
                "Faslodex (fulvestrant)",
                "Femara (letrozole)",
                "Fludara (fludarabine)",
                "FUDR (floxuridine)",
                "Gleevec (imatinib mesylate)",
                "Herceptin (trastuzumab)",
                "Hexalen (altretamine)",
                "Hycamtin (topotecan)",
                "Hydrea (hydroxyurea)",
                "Idamycin (idarubicin)",
                "Ifex (ifosfamide)",
                "Iressa (gefitinib)",
                "Camptosar (irinotecan)",
                "Elspar (asparaginase)",
                "Leukeran (chlorambucil)",
                "Leukine (sargramostim)",
                "Leustatin (cladribine)",
                "Lupron (leuprolide)",
                "Matulane (procarbazine)",
                "Mesnex (mesna)",
                "Meticorten (prednisone)",
                "Myleran (busulfan)",
                "Navelbine (vinorelbine)",
                "Neulasta (pegfilgrastim)",
                "Neupogen (filgrastim)",
                "Nipent (pentostatin)",
                "Nitrogen Mustard (mechlorethamine)",
                "Novaldex (tamoxifen)",
                "Novantrone (mitoxantrone)",
                "Oncaspar (pegaspargase)",
                "Oncovin (vincristine)",
                "Panretin (alitretinoin)",
                "Paraplatin (carboplatin)",
                "Proleukin (aldesleukin)",
                "Purinethol (mercaptopurine)",
                "Retina-A (tretinoin)",
                "Rituxan (rituximab)",
                "Roferon-A (interferon alfa-2a)",
                "Sandostatin (octreotide)",
                "SPRYCEL (dasatinib)",
                "Tabloid (thioguanine)",
                "Targretin (bexarotene)",
                "Taxotere (docetaxel)",
                "Temodar (temozolomide)",
                "Thalomid (thalidomide)",
                "TICE BCG (bcg)",
                "Toposar (etoposide)",
                "Torisel (temsirolimus)",
                "Trexall (methotrexate)",
                "Trisenox (arsenic trioxide)",
                "TYKERB (lapatinib)",
                "Vectibix (panitumumab)",
                "Velban (vinblastine)",
                "Velcade (bortezomib)",
                "Vidaza (azacitidine)",
                "Vumon (teniposide)",
                "Zanosar (streptozocin)",
                "Zoladex (goserelin)",
                "Zometa (zoledronic acid)"
            ]
        </script>

		<%-- include jQuery Templates; if the page is readonly (!isEditable), only a subset of templates will be included --%>
		<jsp:include page="templates.jsp">			
			<jsp:param name="isEditable" value="${isEditable}" />
		</jsp:include> 
		
		<%-- include the correct Javascript files --%>
		<c:choose>
			<c:when test="${requestScope.debugMode == true}">
				<%-- include the unminified JS files since an admin is debugging this page --%>
				<c:choose>
					<c:when test="${isEditable}">
						<%@ include file="/jspf/timelineJSEditableRaw.jspf" %>
					</c:when>
					<c:otherwise>				
						<%@ include file="/jspf/timelineJSReadonlyRaw.jspf" %>
					</c:otherwise>
				</c:choose>		
			</c:when>
			<c:otherwise>
				<%-- include the minified JS files - end user demands max performance! :) --%>
				<c:choose>
					<c:when test="${isEditable}">
						<c:choose>
							<c:when test="${requestScope.localJQueryMode == true}">
								<%-- should probably be a minified version! --%>
								<script src="/js/jquery-1.8.3.js" type="text/javascript"></script>							
							</c:when>
							<c:otherwise>
								<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
							</c:otherwise>
						</c:choose>		
										
						<%@ include file="/jspf/timelineJSEditableMinified.jspf" %>
						
					</c:when>
					<c:otherwise>
						<c:choose>
							<c:when test="${requestScope.localJQueryMode == true}">
								<%-- should probably be a minified version! --%>
								<script src="/js/jquery-1.8.3.js" type="text/javascript"></script>
							</c:when>
							<c:otherwise>
								<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
							</c:otherwise>
						</c:choose>						
						
						<%@ include file="/jspf/timelineJSReadonlyMinified.jspf" %>
						
					</c:otherwise>
				</c:choose>		
			</c:otherwise>
		</c:choose> 
 
        
    </head>
    <body>
        
		<%@ include file="/jspf/header.jspf" %>
		<%-- errorsDialog cannot be in the header since header is also used on readonly pages, which cannot have errors --%>
		<div id="errorsDialog" class="dialog" title="Errors Dialog">
		    <p class="valid">Nice job!  You&apos;ve now filled in all of the required information correctly, so you should have no trouble submitting the data now.</p>
		    <p class="invalid" style="display: none">Hey there!  Just correct these minor problems and everything should work!</p>
		    <ul class="errors"></ul>
		</div>

        <div id="sidebar">
        	<div id="eventInfoBox">
        		<div id="eventInfoTabs" class="tabs">
        			<ul>
                        <li><a href="#eventInfoTabs-diagnosis">Diagnoses</a></li>
        				<li><a href="#eventInfoTabs-surgery" >Surgery</a></li>
        				<li><a href="#eventInfoTabs-chemotherapy" >Chemo</a></li>
        				<li><a href="#eventInfoTabs-radiation" >Radiation</a></li>
        				<!--<li><a href="#eventInfoTabs-immunotherapy" >Cell Therapy</a></li>-->
        				<li><a href="#eventInfoTabs-test" >Test</a></li>
        			</ul>
                    <div class="spacer" style="height: 20px">
 
                    </div>

                    <div id="eventInfoTabs-diagnosis" class="eventTypeContent Diagnosis ">
                        <div class="eventTypeVisibilityToggle">
                            <span class="visibilityToggleLabel">Show Diagnoses on Timeline? </span>
                            <input type="radio" name="diagnosisToggle" id="0_checked" value="show" checked="checked"/>
                            <label for="0_checked">&#x2714;</label>
                            <input type="radio" name="diagnosisToggle" id="0_unchecked" value="hide" />
                            <label for="0_unchecked">&#x2716;</label><br/>
                        </div>
                        <ul />
                    </div>

        			<!--<div id="eventInfoTabs-surgery" class="accordion">-->
                    <div id="eventInfoTabs-surgery" class="eventTypeContent Surgery hidden">
                        <div class="eventTypeVisibilityToggle">
                            <span class="visibilityToggleLabel">Show Surgeries on Timeline? </span>
                            <input type="radio" name="surgeriesToggle" id="1_checked" value="show" checked="checked"/>
                            <label for="1_checked">&#x2714;</label>
                            <input type="radio" name="surgeriesToggle" id="1_unchecked" value="hide" />
                            <label for="1_unchecked">&#x2716;</label><br/>
                        </div>                      
                        <ul />
        			</div>
        			<div id="eventInfoTabs-chemotherapy" class="eventTypeContent Chemo hidden">
                        <div class="eventTypeVisibilityToggle">
                            <span class="visibilityToggleLabel">Show Chemotherapies on Timeline? </span>
                            <input type="radio" name="chemosToggle" id="2_checked" value="show" checked="checked"/>
                            <label for="2_checked">&#x2714;</label>
                            <input type="radio" name="chemosToggle" id="2_unchecked" value="hide" />
                            <label for="2_unchecked">&#x2716;</label><br/>
                        </div>
                        <ul />    				
        			</div>
        			<div id="eventInfoTabs-radiation" class="eventTypeContent Radiation " style="display: none">
                        <div class="eventTypeVisibilityToggle">
                            <span class="visibilityToggleLabel">Show Radiation Events on Timeline? </span>
                            <input type="radio" name="radiationToggle" id="3_checked" value="show" checked="checked"/>
                            <label for="3_checked">&#x2714;</label>
                            <input type="radio" name="radiationToggle" id="3_unchecked" value="hide" />
                            <label for="3_unchecked">&#x2716;</label><br/>                         
                        </div>
                        <ul />
        			</div>
        			<div id="eventInfoTabs-immunotherapy" class="eventTypeContent Immuno " style="display: none">
                        <div class="eventTypeVisibilityToggle">
                            <span class="visibilityToggleLabel">Show Cell Therapies on Timeline ?</span>
                            <input type="radio" name="immunosToggle" id="4_checked" value="show" checked="checked"/>
                            <label for="4_checked">&#x2714;</label>
                            <input type="radio" name="immunosToggle" id="4_unchecked" value="hide" />
                            <label for="4_unchecked">&#x2716;</label><br/>
                        </div>
                        <ul />
        			</div>
        			<div id="eventInfoTabs-test" class="eventTypeContent Test">
                        <div class="eventTypeVisibilityToggle">
                            <span class="visibilityToggleLabel">Show Tests on Timeline ?</span>
                            <input type="radio" name="testsToggle" id="5_checked" value="show" checked="checked"/>
                            <label for="5_checked">&#x2714;</label>
                            <input type="radio" name="testsToggle" id="5_unchecked" value="hide" />
                            <label for="5_unchecked">&#x2716;</label><br/>
                        </div>
                        <ul />
        			</div>                        			        			 
        		</div>
        	</div>
    	</div>
        <div id="main">
            <div id="my-timeline" class="timeline ui-widget ui-widget-content ui-corner-all" style="color: black;"></div>

            <div id="patientNotesContainer" class="ui-widget ui-widget-content ui-corner-all">
                <div id="patientNotesHeader">
                    <h3>In My Own Words:</h3>
                    <span class="msgBox" style="display: none">Oops!  There are a couple of <a class='errorsDialogLink'>errors</a></span>
                </div>
                <div id="patientNotesMain">
                    <div id="patientNotesNav" class="ui-widget ui-widget-content ui-corner-all">
                    </div>
                    <div id="patientNotes">
                        <ul />
                    </div>
                </div>
            </div>            
        </div>
        <div id="theAbyss" style="display:none">
            <div class="hidden">put stuff here that will never be seen</div>
        </div>
        <noscript>
            This page uses Javascript to show you a Timeline. Please enable Javascript in your browser to see the full page. Thank you.
        </noscript>
    </body>
</html>
